// demo-vue/app/components/Static.vue
<template>
	<Page>
		<ActionBar title="Static"/>
		<StackLayout iosOverflowSafeArea="false">
			<Pager height="100%" selectedIndex="1">
				<PagerItem backgroundColor="red">
					<Label text="First"></Label>
				</PagerItem>
				<PagerItem backgroundColor="white">
					<Label text="Second"></Label>
				</PagerItem>
				<PagerItem backgroundColor="black">
					<Label text="Third" color="white"></Label>
				</PagerItem>
				<PagerItem backgroundColor="green">
					<Label text="Fourth"></Label>
				</PagerItem>
			</Pager>
		</StackLayout>
	</Page>
</template>

<script>
	export default {};
</script>

<style scoped>
	ActionBar {
		background-color: #53ba82;
		color: #ffffff;
	}

	.message {
		vertical-align: center;
		text-align: center;
		font-size: 20;
		color: #333333;
	}
</style>

// demo-ng/app/static/static.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'ns-static',
    moduleId: module.id,
    templateUrl: './static.component.html',
    styleUrls: ['static.component.css']
})
export class StaticComponent {
    currentPagerIndex = 5;
}
<ActionBar title="Static" class="action-bar">
</ActionBar>
<GridLayout rows="auto,*" columns="*" class="page">
	<Button text="Single Template" [nsRouterLink]="['/test']" class="btn btn-primary"></Button>
	<Pager backgroundColor="orange" row="1" #pager [selectedIndex]="1" height="100%">
		<StackLayout *pagerItem backgroundColor="red">
			<Label text="First"></Label>
		</StackLayout>
		<StackLayout *pagerItem backgroundColor="white">
			<Label text="Second"></Label>
		</StackLayout>
		<StackLayout *pagerItem backgroundColor="black">
			<Label text="Third" color="white"></Label>
		</StackLayout>
		<StackLayout *pagerItem backgroundColor="green">
			<Label text="Fourth"></Label>
		</StackLayout>
	</Pager>
</GridLayout>
